# -----------------------------------------------------------
# 第二部分：随机商店抽取池与每日更新逻辑
#
# 如果 触发每日刷新逻辑
# 则 从 pool.selling 中根据权重随机抽取 10 项作为今日出售商品
# 并 从 pool.buying 中根据权重随机抽取 10 项作为今日收购商品
#
# 如果 物品节点包含 weight 属性
# 则 在抽取时该数值越高，被选中的概率越大
#
# 最后 初始池子保持为空，等待后续指令动态存入物品数据。
# -----------------------------------------------------------

pool:
  selling: {}
  buying: {}

current_daily:
  last_update: "2026-05-06"
  items_selling: []
  items_buying: []